name: Latest stack overflow activity
on:
  schedule:
    # Runs every 5 minutes
    - cron: '*/5 * * * *'
  workflow_dispatch:
permissions:
  contents: write
  
jobs:
  update-readme-with-stack-overflow:
    name: Update this repo's README with latest activity from Dev.to
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gautamkrishnar/blog-post-workflow@v1
        with:
          comment_tag_name: "Website"
          commit_message: "Updated readme with the latest stackOverflow data"
          feed_list: "https://mywild.work/rss/latest-posts, https://dev.to/feed/djacidfx"
